version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-type: "all"
    allow:
      - dependency-type: "security"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    
