[project]
name = "maya"
version = "1.3.821"
description = "Aarhus City Archives client for generating individual browser-based GUI-clients"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "anyio==4.5.0", "apscheduler==3.11.0", "arrow==1.3.0", "attrs==22.2.0", "autopep8==2.0.1", "beautifulsoup4==4.12.2", "black==24.3.0", "certifi==2024.8.30", "charset-normalizer==3.0.1", "click==8.1.7", "concurrent-log-handler==0.9.25", "exceptiongroup==1.2.2", "flake8==7.2.0", "gunicorn==23.0.0", "h11==0.16.0", "httpcore==1.0.9", "httpx==0.27.2", "idna==3.7", "itsdangerous==2.1.2", "jinja2==3.1.6", "markdown==3.7", "markupsafe==2.1.5", "mccabe==0.7.0", "mypy==1.1.1", "mypy-extensions==1.0.0", "packaging==24.1", "pathspec==0.11.0", "platformdirs==3.0.0", "portalocker==2.10.1", "pycodestyle==2.13.0", "pycparser==2.20", "pyflakes==3.3.2", "python-dateutil==2.9.0.post0", "python-dotenv==0.21.1", "python-multipart==0.0.18", "pyyaml==6.0.2", "rfc3986==1.5.0", "sentry-sdk==2.14.0", "six==1.17.0", "sniffio==1.3.0", "soupsieve==2.5", "starception==1.2.1", "starlette==0.40.0", "starsessions==2.1.1", "toml==0.10.2", "tomli==2.0.1", "types-markdown==3.5.0.20240106", "types-python-dateutil==2.9.0.20241003", "types-pyyaml==6.0.12.8", "types-requests==2.28.11.15", "types-toml==0.10.8.7", "types-urllib3==1.26.25.8", "typing-extensions==4.12.2", "tzlocal==5.2", "urllib3==1.26.19", "uv==0.7.3", "uvicorn==0.30.6", "watchfiles==0.24.0",]
[[project.authors]]
name = "Aarhus Stadsarkiv"
email = "stadsarkiv@aarhus.dk"

[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project.scripts]
maya = "maya.commands.cli:cli"

[tool.setuptools]
include-package-data = true

[tool.black]
line-length = 140

[tool.mypy]
exclude = [ ".venv", "tests", "example-config", "build", "bin-local", "sites",]

[tool.bump_version]
version_file = "maya/__init__.py"

[tool.setuptools.package-data]
maya = [ "locales/**", "templates/**", "static/**", ".env-dist",]

[tool.setuptools.packages.find]
where = [ ".",]
exclude = [ "tests",]

[tool.bump_version.replace_patterns.pip]
file = "sites/demo-readonly/docs/01-maya.md"
search = "<!-- LATEST-VERSION-PIP -->"
replace = "\tpip install git+https://github.com/aarhusstadsarkiv/stadsarkiv-client@{version}\n"

[tool.bump_version.replace_patterns.pipx]
file = "sites/demo-readonly/docs/01-maya.md"
search = "<!-- LATEST-VERSION-PIPX -->"
replace = "\tpipx install git+https://github.com/aarhusstadsarkiv/stadsarkiv-client@{version}\n"
