[tool.poetry]
name = "stadsarkiv-client"
version = "0.1.0"
description = "A generic starlette client for our Fastapi-webservice"
authors = ["Aarhus City Archive <stadsarkiv@aarhus.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 140
[tool.mypy]
exclude = ['venv', '.venv', 'generate_openaws_client', 'tests', 'example-config']
