[tool.black]
line-length = 140

[tool.mypy]
exclude = [ "venv", ".venv", "generate_openaws_client", "tests", "example-config", "build", "bin-local",]

[tool.bump_version]
version_file = "maya/__init__.py"

[tool.bump_version.replace_patterns.pip]
file = "example-config-demo/docs/README.md"
search = "<!-- LATEST-VERSION-PIP -->"
replace = "\tpip install git+https://github.com/aarhusstadsarkiv/stadsarkiv-client@{version}\n"

[tool.bump_version.replace_patterns.pipx]
file = "example-config-demo/docs/README.md"
search = "<!-- LATEST-VERSION-PIPX -->"
replace = "\tpipx install git+https://github.com/aarhusstadsarkiv/stadsarkiv-client@{version}\n"
