client_name: aarhusarkivet
client_url: https://aarhusarkivet.openaws.dk
language: da
log_handlers: [rotating_file]  # ["stream"]
cookie: {name: session, lifetime: 3600, httponly: true, secure: true, samesite: lax}
api_base_url: https://api.openaws.dk/v1

# Custom pages
#
# "name" is the route name.
# "title" is the page title.
# "template" is the page you will use. It is also the content of the page.
# "url" is the path to the page.
# "type" is the type of menu item. It can be "top" or "overlay". If it is not set, it will not be displayed in the menu.
pages:
  - {name: home, title: Hjem, template: pages/home.html, url: "/"}
  - {name: page_images, title: Hjemmesider med billeder fra Aarhus, template: pages/images.html, url: /images}
  - {name: page_council, title: Aarhus Byråds arkiv, template: pages/city-council.html, url: /city-council}
  - {name: page_searchguide, title: Hjælp til søgning, template: pages/guides/searchguide.html, url: /guides/searchguide}
  - {name: page_genealogy, title: Slægtsforskning, template: pages/guides/genealogy.html, url: /guides/genealogy}
  - {name: page_municipality_records, title: Kommunearkivet, template: pages/guides/municipality_records.html, url: /guides/municipality_records}
  - {name: page_collections, title: Om samlingerne, template: pages/about/collections.html, url: /about/collections}
  - {name: page_availability, title: Tilgængelighed, template: pages/about/availability.html, url: /about/availability}
  - {name: page_archival_availability, title: Arkivlovens tilgængelighedsfrister, template: pages/about/archival_availability.html, url: /about/archival_availability}
  - {name: page_usability, title: Brugbarhed, template: pages/about/usability.html, url: /about/usability}
  - {name: page_privacy, title: Privatlivspolitik, template: pages/about/privacy.html, url: /about/privacy}

main_menu_top:
  - {name: search_get, title: Søg, type: icon, icon: search}

main_menu_system:
  - {name: auth_login_get, title: Log ind}
  - {name: auth_logout_get, title: Log ud}
  - {name: auth_register_get, title: Ny bruger}
  - {name: auth_me_get, title: Profil}
  - {name: admin_users_get, title: Brugere}
  - {name: schemas_get_list, title: Skemaer}
  - {name: entities_get_list, title: Entiteter}

main_menu_sections:
  - name: guides
    title: Vejledninger
    pages:
      - {name: page_searchguide, title: Hjælp til søgning}
      - {name: page_genealogy, title: Slægtsforskning}
      - {name: page_municipality_records, title: Kommunearkivet}
  - name: about
    title: Om samlingerne
    pages:
      - {name: page_collections, title: Om samlingerne}
      - {name: page_availability, title: Tilgængelighed}
      - {name: page_archival_availability, title: Arkivlovens tilgængelighedsfrister, url: /about/archival_availability}
      - {name: page_usability, title: Brugbarhed}
      - {name: page_privacy, title: Privatlivspolitik}

robots_allow: false
allow_user_registration: true
allow_user_management: true
allow_online_ordering: true
allow_save_bookmarks: true
