name: Python Test

on:
  push:
    branches:
      - main  # Change this to your branch name if needed
    paths-ignore:
      - '*.md'
      - 'docs/*'
      - 'example-config/*'
      - '**/*.draft.md'
      - 'example-schemas/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install locales
        run: sudo apt-get install -y locales && sudo locale-gen da_DK.UTF-8

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run default client tests
        run: python -m unittest tests/config-default/*.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
        # env:
        # CONFIG_DIR: example-config-aarhus

      - name: Run teater client tests
        run: python -m unittest tests/config-teater/*.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG_DIR: example-config-teater

      - name: Run aarhus client tests
        run: python -m unittest tests/config-aarhus/*.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG_DIR: example-config-aarhus
        
      - name: Run mypy
        run: mypy --config-file pyproject.toml .
      