name: Python Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install locales
        run: sudo apt-get install -y locales && sudo locale-gen da_DK.UTF-8

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run tests
        run: .venv/bin/python -m maya source-test
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run mypy
        run: .venv/bin/mypy --config-file pyproject.toml .
